### ISSUE TITLE
Memory Ribbons don't show up

### ISSUE THREAD

**Issue by Raia** [not-an-aardvark/pk6parse#11]
pk6parse returns `ribbonData: 0` and an empty array for `ribbons` for Pokémon that have only Memory Ribbons.

Info:
- http://bulbapedia.bulbagarden.net/wiki/List_of_Ribbons_in_the_games#Battle_Memory_Ribbons
- http://bulbapedia.bulbagarden.net/wiki/List_of_Ribbons_in_the_games#Contest_Memory_Ribbons

Sample pk6 files:
- [Maxed past ribbons (40 contest, 8 battle)](https://www.dropbox.com/s/2sbwaimnburuiji/memory%20ribbons%20-%20all.pk6?dl=0)
- [Half-maxed past ribbons (20 contest, 4 battle)](https://www.dropbox.com/s/wbumcv55qzzvpxq/memory%20ribbons%20-%20half.pk6?dl=0)

**Comment by AlMcKinlay** [comment]
Oh, woops. Sorry, naa, I didn't realise this was on pk6parse repo. It appeared in waffle :-\
