### ISSUE TITLE
Add support for updated Pokémon Bank

### ISSUE THREAD

**Issue by Raia** [not-an-aardvark/pk6parse#14]
>I've hacked in a few Eevees with game origins between 0x20 and 0x29. 0x20 and 0x21 shows Alola native. 0x22 shows a G in a circle, 0x23 is the GB icon recently revealed by Nintendo HK.

>(0x23 to 0x29 for the GB icon)

Special characters have changed too. There's some info in kwsch/PKHeX#734.

related: porygonco/porybox#609

**Comment by AlMcKinlay** [comment]
I'm going to split this up into multiple issues.

**Comment by AlMcKinlay** [comment]
As far as I can see, this is #19 and #20.

Feel free to create another issue if I've missed something.
